CREATE TABLE events (
	id int4 NOT NULL,
	"name" varchar(50) NULL,
	deadline_time timestamp NULL,
	average_entry_score int4 NULL,
	finished bool NULL,
	data_checked bool NULL,
	highest_scoring_entry int8 NULL,
	deadline_time_epoch int8 NULL,
	deadline_time_game_offset int4 NULL,
	highest_score int4 NULL,
	is_previous bool NULL,
	is_current bool NULL,
	is_next bool NULL,
	bboost_played int8 NULL,
	trip_cap_played int8 NULL,
	wildcard_played int8 NULL,
	freehit_played int8 NULL,
	most_selected varchar(50) NULL,
	most_transferred_in varchar(50) NULL,
	top_player varchar(50) NULL,
	top_player_points int4 NULL,
	transfers_made int8 NULL,
	most_captained varchar(50) NULL,
	most_vice_captained varchar(50) NULL
);

CREATE TABLE gwhistory (
	"element" int4 NOT NULL,
	player_name varchar(50) NULL,
	fixture int4 NOT NULL,
	opponent_team varchar(50) NULL,
	total_points int4 NULL,
	was_home int2 NULL,
	minutes int4 NULL,
	goals_scored int4 NULL,
	assists int4 NULL,
	clean_sheets int4 NULL,
	goals_conceded int4 NULL,
	own_goals int4 NULL,
	penalties_saved int4 NULL,
	penalties_missed int4 NULL,
	yellow_cards int4 NULL,
	red_cards int4 NULL,
	saves int4 NULL,
	bonus int4 NULL,
	bps int4 NULL,
	influence float8 NULL,
	creativity float8 NULL,
	threat float8 NULL,
	ict_index float8 NULL,
	value int4 NULL,
	transfers_balance int4 NULL,
	selected int4 NULL,
	transfers_in int4 NULL,
	transfers_out int4 NULL
);

CREATE TABLE league (
	id int8 NOT NULL,
	event_total int4 NULL,
	player_name varchar(100) NULL,
	"rank" int4 NULL,
	last_rank int4 NULL,
	rank_sort int4 NULL,
	total int4 NULL,
	entry int8 NULL,
	entry_name varchar(100) NULL,
	CONSTRAINT pk_league PRIMARY KEY (id)
);

CREATE TABLE players (
	id int4 NOT NULL,
	web_name varchar(50) NULL,
	first_name varchar(50) NULL,
	second_name varchar(50) NULL,
	chance_of_playing_next_round int4 NULL,
	chance_of_playing_this_round int4 NULL,
	code int4 NULL,
	cost_change_event int4 NULL,
	cost_change_event_fall int4 NULL,
	cost_change_start int4 NULL,
	cost_change_start_fall int4 NULL,
	dreamteam_count int4 NULL,
	"position" varchar(50) NULL,
	ep_next float8 NULL,
	ep_this float8 NULL,
	event_points float8 NULL,
	form float8 NULL,
	in_dreamteam bool NULL,
	news varchar(150) NULL,
	news_added timestamp NULL,
	now_cost int4 NULL,
	points_per_game float8 NULL,
	selected_by float8 NULL,
	special bool NULL,
	squad_number int4 NULL,
	status varchar(50) NULL,
	team varchar(50) NULL,
	team_code int4 NULL,
	total_points int4 NULL,
	transfers_in int4 NULL,
	transfers_in_event int4 NULL,
	transfers_out int4 NULL,
	transfers_out_event int4 NULL,
	value_form float8 NULL,
	value_season float8 NULL,
	minutes int4 NULL,
	goals_scored int4 NULL,
	assists int4 NULL,
	clean_sheets int4 NULL,
	goals_conceded int4 NULL,
	own_goals int4 NULL,
	penalties_saved int4 NULL,
	penalties_missed int4 NULL,
	yellow_cards int4 NULL,
	red_cards int4 NULL,
	saves int4 NULL,
	bonus int4 NULL,
	bps int4 NULL,
	influence float8 NULL,
	creativity float8 NULL,
	threat float8 NULL,
	ict_index float8 NULL,
	influence_rank int4 NULL,
	influence_rank_type int4 NULL,
	creativity_rank int4 NULL,
	creativity_rank_type int4 NULL,
	crners_fkicks_order int4 NULL,
	crners_fkicks_note varchar(50) NULL,
	fkicks_order int4 NULL,
	fkicks_note varchar(50) NULL,
	pens_order int4 NULL,
	pens_note varchar(50) NULL,
	CONSTRAINT pk_players PRIMARY KEY (id)
);

